{
 "title": "web app",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "DNS Resolve Failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "dns_failed_resolve_total{container=\"web-app\", job=\"web-app-service\", namespace=\"web-app\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "dns_cache_hits_total{container=\"web-app\", job=\"web-app-service\", namespace=\"web-app\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "dns_cache_misses_total{container=\"web-app\", job=\"web-app-service\", namespace=\"web-app\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (Per Pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"web-app\", container=\"web-app\", job=\"web-app-service\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resident Memory Usage in MB ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"web-app\", pod=\"web-app-deployment-6758c56c74-ghw9w\", container=\"web-app\"} / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual Memory Usage in MB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{namespace=\"web-app\", pod=\"web-app-deployment-6758c56c74-ghw9w\", container=\"web-app\"} / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}