replicaCount: 1

namespace: web-app 

image:
  repository: ghcr.io/alifattahi/go-dns-resolver
  tag: main-latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8585
  nodePort: 30085  

env:
  SERVER_PORT: 8585
  DATABASE_URL: "postgresql://web-app-pg-cluster-rw.web-app-db:5432/app?password=CblVhWcqk0mujecx1F62RaVvHEo9DPoixxcd8vzxGgzjwWNrLMtraW9hphrm1v41&user=app"
resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

prometheus:
  enabled: true
  path: /metrics
  interval: 30s
  scheme: http
  tlsConfig: null 
  servicemonitor:
    labels: {}


ingress:
  enabled: true
  name: "dns-resolver-ingress"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: dns-resolver-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - secretName: dns-resolver-tls
      hosts:
        - dns-resolver-app.local


