replicaCount: 1
namespace: web-app
image:
  repository: ghcr.io/alifattahi/go-dns-resolver
  tag: main-20e979f
  pullPolicy: Always
service:
  type: NodePort
  port: 8585
  nodePort: 30085
env:
  SERVER_PORT: 8585
  secrets:
    DATABASE_URL: AgAcQ49xsGMn2jVIJQnhCdZRJp6951Wmc6i4PKJbsB8Fr4da1jglhqnYxNijGFXEfktDDSa+EvpBeLdGvQspgZWypod/2EtTRIZt1cIwLBhxuAnXlI/1clF1dEXm0Wl0u8+TqKaD2j08nLum1XfxhCoR0pIIpxyZ2EhxWjjuKDSsKKE55YZnv0HoSG/ubrOWfSm4PMkUzRzxS0z6W8DhgxHM85/wvtPQ2rQLYnowulbcbYgkUG3GCk8iOqAnN4WrHXglOF4CoPyGnVQL26csjAUpsyhYJCopTXV5TBJPmDo023/UH4ZDEQh8RzuQdEXVJ9Vcuz+9sDzn+NuKVdMiQ+x7B2tTF/TbSTEFQ9UBHq3zAXZ99VWnuexAhCDx/x6G19v9Y7SXgzETJhtWtyfhbukK1GgHINIctdGFDal4Dtb/41E8rk9Qktp4KX1ojKb4sIPmn+XiF7TkDl29sMHYtgwNgL6H7XxOjyUBkU+XWkU7rheQQndMgq4HddDI5SkdnXtVPgaSEv+B1xoHCUe+rZXj/qygnKQK1LcSp+EYwpQWTUvlmEDOBhYrPFVB/4fG4GTdvArh3dxjtYg/sp5FUhCBdP2FogkGvto3nbJc8bFXdLSWEJyiPhqjeiT1O6togESaYoYRdE1eQf5JXJaFkofN2jif08AUxzErI27uJ0613QaHins/lwG3wEyA8DYi+pDhmv4zCUqewkiAUuYhiOxuBc4yLUj8vDynch27ClGvLv2fOLoeC4sJYQI4rp4OQ9zlpjGSBRUrkoI49oNEssD/qvHUtVd9Czcp4K0mzQ7Jbc2ZP6Bs/1l8ZzlELoxsOp1xvgJDxilm1qorsm4miYN0TxH3YoMZNMUFSyo=
resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"
prometheus:
  enabled: true
  path: /metrics
  interval: 30s
  scheme: http
  tlsConfig: null
  servicemonitor:
    labels: {}
ingress:
  enabled: true
  name: "dns-resolver-ingress"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: dns-resolver-app.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: dns-resolver-tls
      hosts:
        - dns-resolver-app.local
