replicaCount: 1

image:
  repository: ghcr.io/alifattahi/go-dns-resolver
  tag: main-latest
  pullPolicy: Always

service:
  name: dns-resolver-app-service
  type: ClusterIP
  port: 80

env:
  SERVER_PORT: 8585
  DATABASE_URL: "postgresql://username:password@your-database-host/your-database-name"

resources: {}

ingress:
  enabled: false
  name: ""
  annotations: {}
  hosts:
    - host: dns-resolver-app.local
      paths: []
  tls: []

prometheus:
  enabled: true
  path: "/metrics"
  port: "8585"

