apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | b64enc | quote }}
